spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    org.springframework.security: DEBUG

